const electron = require('electron');
const dialog = electron.dialog;
const sqlite3 = require('sqlite3').verbose();
export const db = new sqlite3.Database('db.sqlite3');

export const setupDatabase = () => {
  db.serialize(()=>{
    createTableProvinces();
    createTableDistricts();
    createTableCustomers();
  });

  dialog.showMessageBox({type: 'info', title: 'Thông báo', message: 'Đã khởi tạo Database thành công, bạn có thể tiếp tục sử dụng ứng dụng.'});
}

export const importData = () => {
  db.serialize(()=>{
    insertTableProvinces();
    insertTableDistricts();
  });

  dialog.showMessageBox({type: 'info', title: 'Thông báo', message: 'Import dữ liệu thành công.'});
}

function createTableProvinces() {
  db.run('DROP TABLE IF EXISTS provinces;');
  db.run('CREATE TABLE provinces(provinceId INTEGER PRIMARY KEY, name TEXT);');
}

function createTableDistricts() {
  db.run('DROP TABLE IF EXISTS districts;');
  db.run('CREATE TABLE districts(districtId INTEGER PRIMARY KEY, name TEXT, provinceId INTEGER, FOREIGN KEY(provinceId) REFERENCES provinces(provinceId));');
}

function createTableCustomers() {
  db.run('DROP TABLE IF EXISTS customers;');
  db.run('CREATE TABLE customers(customerId INTEGER PRIMARY KEY AUTOINCREMENT, customerIndex Integer, firstName TEXT, lastName TEXT, districtId INTEGER, provinceId INTEGER, districtName TEXT, provinceName TEXT, schoolName TEXT, phoneNumber TEXT, parentPhoneNumber TEXT, collectedDate TEXT, collectedTime TEXT, dateOfBirth TEXT, yearOfBirth Integer, brand TEXT, subBrand TEXT, samplingProduct TEXT, gender INTEGER, optIn INTEGER, source TEXT, batch TEXT,\
    hasError INTEGER DEFAULT 0,\
    missingData INTEGER DEFAULT 0,\
    missingName INTEGER DEFAULT 0,\
    missingLivingCity INTEGER DEFAULT 0,\
    missingContactInformation INTEGER DEFAULT 0,\
    missingAge INTEGER DEFAULT 0,\
    missingCollectedDate INTEGER DEFAULT 0,\
    missingSchoolName INTEGER DEFAULT 0,\
    missingBrandUsing INTEGER DEFAULT 0,\
    missingSamplingType INTEGER DEFAULT 0,\
    illogicalData INTEGER DEFAULT 0,\
    illogicalPhone INTEGER DEFAULT 0,\
    illogicalAge INTEGER DEFAULT 0,\
    illogicalAgePupil INTEGER DEFAULT 0,\
    illogicalAgeStudent INTEGER DEFAULT 0,\
    duplicatedPhone INTEGER DEFAULT 0,\
    duplicatedPhoneBetweenPupilAndStudent INTEGER DEFAULT 0,\
    duplicatedPhoneWithinPupil INTEGER DEFAULT 0,\
    duplicatedPhoneWithinStudent INTEGER DEFAULT 0,\
    FOREIGN KEY(districtId) REFERENCES districts(districtId),\
    FOREIGN KEY(provinceId) REFERENCES provinces(provinceId));');
}

function insertTableProvinces() {
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 1, 'An Giang');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 2, 'Bắc Cạn');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 3, 'Bình Dương');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 4, 'Bình Định');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 5, 'Bắc Giang');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 6, 'Bạc Liêu');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 7, 'Bắc Ninh');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 8, 'Bình Phước');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 9, 'Bến Tre');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 10, 'Bình Thuận');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 11, 'Cao Bằng');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 12, 'Cà Mau');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 13, 'Cần Thơ');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 14, 'Điện Biên');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 15, 'Đắc Lắc');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 16, 'Đà Nẵng');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 17, 'Đồng Nai');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 18, 'Đắc Nông');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 19, 'Đồng Tháp');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 20, 'Gia Lai');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 21, 'Hà Nội');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 22, 'Hòa Bình');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 23, 'Hồ Chí Minh');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 24, 'Hải Dương');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 25, 'Hà Giang');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 26, 'Hậu Giang');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 27, 'Hà Nam');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 28, 'Hải Phòng');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 29, 'Hà Tĩnh');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 31, 'Hưng Yên');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 32, 'Kiên Giang');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 33, 'Khánh Hòa');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 34, 'Kon Tum');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 35, 'Long An');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 36, 'Lào Cai');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 37, 'Lai Châu');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 38, 'Lâm Đồng');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 39, 'Lạng Sơn');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 40, 'Nghệ An');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 41, 'Ninh Bình');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 42, 'Nam Định');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 43, 'Ninh Thuận');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 44, 'Phú Thọ');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 45, 'Phú Yên');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 46, 'Quảng Bình');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 47, 'Quảng Ngãi');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 48, 'Quảng Ninh');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 49, 'Quảng Nam');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 50, 'Quảng Trị');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 51, 'Sơn La');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 52, 'Sóc Trăng');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 53, 'Thái Bình');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 54, 'Tiền Giang');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 55, 'Thanh Hóa');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 56, 'Tây Ninh');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 57, 'Thái Nguyên');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 58, 'Tuyên Quang');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 59, 'Huế');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 60, 'Trà Vinh');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 61, 'Vĩnh Long');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 62, 'Vĩnh Phúc');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 63, 'Bà Rịa - Vũng Tàu');
  db.run('INSERT INTO provinces(provinceId, name) VALUES(?, ?);', 64, 'Yên Bái');
}

function insertTableDistricts() {
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 1, 'A Lưới', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 2, 'An Biên', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 3, 'An Dương', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 4, 'An Khê', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 5, 'An Lão', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 6, 'An Lão', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 7, 'An Minh', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 8, 'An Nhơn', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 9, 'An Phú', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 10, 'Anh Sơn', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 11, 'Ayun Pa', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 12, 'Ân Thi', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 13, 'Ba Bể', 2);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 14, 'Ba Chẽ', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 15, 'Ba Đình', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 16, 'Ba Tơ', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 17, 'Ba Tri', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 18, 'Ba Vì', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 19, 'Bà Rịa', 63);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 20, 'Bá Thước', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 21, 'Bác Ái', 43);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 22, 'Bạc Liêu', 6);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 23, 'Bạch Long Vĩ', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 24, 'Bạch Thông', 2);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 25, 'Bảo Lạc', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 26, 'Bảo Lâm', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 27, 'Bảo Lâm', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 28, 'Bảo Lộc', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 29, 'Bảo Thắng', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 30, 'Bảo Yên', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 31, 'Bát Xát', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 32, 'Bắc Bình', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 33, 'Bắc Giang', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 34, 'Bắc Hà', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 35, 'Bắc Kạn', 2);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 36, 'Bắc Mê', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 37, 'Bắc Ninh', 7);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 38, 'Bắc Quang', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 39, 'Bắc Sơn', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 40, 'Bắc Trà My', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 41, 'Bắc Yên', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 42, 'Bến Cát', 3);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 43, 'Bến Cầu', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 44, 'Bến Lức', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 45, 'Bến Tre', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 46, 'Biên Hòa', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 47, 'Bỉm Sơn', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 48, 'Bình Chánh', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 49, 'Bình Đại', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 50, 'Bình Gia', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 51, 'Bình Giang', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 52, 'Bình Liêu', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 53, 'Bình Long', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 54, 'Bình Lục', 27);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 55, 'Bình Minh', 61);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 56, 'Bình Sơn', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 57, 'Bình Tân', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 58, 'Bình Tân', 61);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 59, 'Bình Thạnh', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 60, 'Bình Thủy', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 61, 'Bình Xuyên', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 62, 'Bố Trạch', 46);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 63, 'Bù Đăng', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 64, 'Bù Đốp', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 65, 'Bù Gia Mập', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 66, 'Buôn Đôn', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 67, 'Buôn Hồ', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 68, 'Buôn Ma Thuột', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 69, 'Cà Mau', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 70, 'Cai Lậy', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 71, 'Cái Bè', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 72, 'Cái Nước', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 73, 'Cái Răng', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 74, 'Cam Lâm', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 75, 'Cam Lộ', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 76, 'Cam Ranh', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 77, 'Can Lộc', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 78, 'Càng Long', 60);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 79, 'Cao Bằng', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 80, 'Cao Lãnh', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 81, 'Cao Lãnh', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 82, 'Cao Lộc', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 83, 'Cao Phong', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 84, 'Cát Hải', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 85, 'Cát Tiên', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 86, 'Cẩm Giàng', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 87, 'Cẩm Khê', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 88, 'Cẩm Lệ', 16);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 89, 'Cẩm Mỹ', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 90, 'Cẩm Phả', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 91, 'Cẩm Thủy', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 92, 'Cẩm Xuyên', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 93, 'Cần Đước', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 94, 'Cần Giờ', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 95, 'Cần Giuộc', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 96, 'Cầu Giấy', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 97, 'Cầu Kè', 60);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 98, 'Cầu Ngang', 60);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 99, 'Châu Đốc', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 100, 'Châu Đức', 63);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 101, 'Châu Phú', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 102, 'Châu Thành', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 103, 'Châu Thành', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 104, 'Châu Thành', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 105, 'Châu Thành', 26);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 106, 'Châu Thành', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 107, 'Châu Thành', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 108, 'Châu Thành', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 109, 'Châu Thành', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 110, 'Châu Thành', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 111, 'Châu Thành', 60);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 112, 'Châu Thành A', 26);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 113, 'Chi Lăng', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 114, 'Chí Linh', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 115, 'Chiêm Hóa', 58);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 116, 'Chợ Đồn', 2);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 117, 'Chợ Gạo', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 118, 'Chợ Lách', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 119, 'Chợ Mới', 2);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 120, 'Chợ Mới', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 121, 'Chơn Thành', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 122, 'Chư Păh', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 123, 'Chư Prông', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 124, 'Chư Pưh', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 125, 'Chư Sê', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 126, 'Chương Mỹ', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 127, 'Con Cuông', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 128, 'Cô Tô', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 129, 'Côn Đảo', 63);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 130, 'Cồn Cỏ', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 131, 'Cờ Đỏ', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 132, 'Cù Lao Dung', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 133, 'Củ Chi', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 134, 'Cư Kuin', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 135, 'Cư Jút', 18);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 136, "Cư M'gar", 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 137, 'Cửa Lò', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 138, 'Dầu Tiếng', 3);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 139, 'Di Linh', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 140, 'Dĩ An', 3);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 141, 'Diên Khánh', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 142, 'Diễn Châu', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 143, 'Duy Tiên', 27);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 144, 'Duy Xuyên', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 145, 'Duyên Hải', 60);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 146, 'Dương Kinh', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 147, 'Dương Minh Châu', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 148, 'Đa Krông', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 149, 'Đà Bắc', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 150, 'Đà Lạt', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 151, 'Đạ Huoai', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 152, 'Đạ Tẻh', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 153, 'Đại Lộc', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 154, 'Đại Từ', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 155, 'Đăk Đoa', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 156, 'Đắk Pơ', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 157, 'Đan Phượng', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 158, 'Đắk Glei', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 159, 'Đăk Glong', 18);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 160, 'Đắk Hà', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 161, 'Đăk Mil', 18);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 162, "Đăk R'Lấp", 18);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 163, 'Đăk Song', 18);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 164, 'Đăk Tô', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 165, 'Đầm Dơi', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 166, 'Đầm Hà', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 167, 'Đam Rông', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 168, 'Đất Đỏ', 63);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 169, 'Điện Bàn', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 170, 'Điện Biên', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 171, 'Điện Biên Đông', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 172, 'Điện Biên Phủ', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 173, 'Đình Lập', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 174, 'Định Hóa', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 175, 'Định Quán', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 176, 'Đoan Hùng', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 177, 'Đô Lương', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 178, 'Đồ Sơn', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 179, 'Đông Anh', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 180, 'Đông Giang', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 181, 'Đông Hà', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 182, 'Đông Hải', 6);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 183, 'Đông Hòa', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 184, 'Đông Hưng', 53);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 185, 'Đông Sơn', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 186, 'Đông Triều', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 187, 'Đồng Hới', 46);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 188, 'Đồng Hỷ', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 189, 'Đồng Phú', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 190, 'Đồng Văn', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 191, 'Đồng Xoài', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 192, 'Đồng Xuân', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 193, 'Đống Đa', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 194, 'Đơn Dương', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 195, 'Đức Cơ', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 196, 'Đức Hòa', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 197, 'Đức Huệ', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 198, 'Đức Linh', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 199, 'Đức Phổ', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 200, 'Đức Thọ', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 201, 'Đức Trọng', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 202, "Ea H'leo", 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 203, 'Ea Kar', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 204, 'Ea Súp', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 205, 'Gia Bình', 7);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 206, 'Gia Lâm', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 207, 'Gia Lộc', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 208, 'Gia Nghĩa', 18);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 209, 'Gia Viễn', 41);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 210, 'Giá Rai', 6);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 211, 'Giang Thành', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 212, 'Giao Thủy', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 213, 'Gio Linh', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 214, 'Giồng Riềng', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 215, 'Giồng Trôm', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 216, 'Gò Công', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 217, 'Gò Công Đông', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 218, 'Gò Công Tây', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 219, 'Gò Dầu', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 220, 'Gò Quao', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 221, 'Gò Vấp', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 222, 'Hà Đông', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 223, 'Hà Giang', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 224, 'Hà Quảng', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 225, 'Hà Tiên', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 226, 'Hà Tĩnh', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 227, 'Hà Trung', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 228, 'Hạ Hòa', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 229, 'Hạ Lang', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 230, 'Hạ Long', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 231, 'Hai Bà Trưng', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 232, 'Hải An', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 233, 'Hải Châu', 16);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 234, 'Hải Dương', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 235, 'Hải Hà', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 236, 'Hải Hậu', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 237, 'Hải Lăng', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 238, 'Hàm Tân', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 239, 'Hàm Thuận Bắc', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 240, 'Hàm Thuận Nam', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 241, 'Hàm Yên', 58);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 242, 'Hậu Lộc', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 243, 'Hiệp Đức', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 244, 'Hiệp Hòa', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 245, 'Hoa Lư', 41);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 246, 'Hòa An', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 247, 'Hoà Bình', 6);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 248, 'Hoà Bình', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 249, 'Hòa Thành', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 250, 'Hoà Vang', 16);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 251, 'Hoài Ân', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 252, 'Hoài Đức', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 253, 'Hoài Nhơn', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 254, 'Hoàn Kiếm', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 255, 'Hoàng Mai', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 256, 'Hoàng Sa', 16);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 257, 'Hoàng Su Phì', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 258, 'Hoành Bồ', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 259, 'Hoằng Hóa', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 260, 'Hóc Môn', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 261, 'Hòn Đất', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 262, 'Hớn Quản', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 263, 'Hội An', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 264, 'Hồng Bàng', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 265, 'Hồng Dân', 6);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 266, 'Hồng Lĩnh', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 267, 'Hồng Ngự', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 268, 'Hồng Ngự', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 269, 'Huế', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 270, 'Hưng Hà', 53);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 271, 'Hưng Nguyên', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 272, 'Hưng Yên', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 273, 'Hương Khê', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 274, 'Hương Sơn', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 275, 'Hương Thủy', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 276, 'Hương Trà', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 277, 'Hướng Hóa', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 278, 'Hữu Lũng', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 279, 'Ia Grai', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 280, 'Ia Pa', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 281, 'KBang', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 282, 'Kế Sách', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 283, 'Khánh Sơn', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 284, 'Khánh Vĩnh', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 285, 'Khoái Châu', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 286, 'Kiên Hải', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 287, 'Kiên Lương', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 288, 'Kiến An', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 289, 'Kiến Thụy', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 290, 'Kiến Xương', 53);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 291, 'Kim Bảng', 27);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 292, 'Kim Bôi', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 293, 'Kim Động', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 294, 'Kim Sơn', 41);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 295, 'Kim Thành', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 296, 'Kinh Môn', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 297, 'Kon Plông', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 298, 'Kon Rẫy', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 299, 'Kon Tum', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 300, 'Kông Chro', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 301, 'Krông Ana', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 302, 'Krông Bông', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 303, 'Krông Búk', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 304, 'Krông Năng', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 305, 'Krông Nô', 18);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 306, 'Krông Pa', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 307, 'Krông Pắk', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 308, 'Kỳ Anh', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 309, 'Kỳ Sơn', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 310, 'Kỳ Sơn', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 311, 'La Gi', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 312, 'Lạc Dương', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 313, 'Lạc Sơn', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 314, 'Lạc Thủy', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 315, 'Lai Châu', 37);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 316, 'Lai Vung', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 317, 'Lang Chánh', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 318, 'Lạng Giang', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 319, 'Lạng Sơn', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 320, 'Lào Cai', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 321, 'Lắk', 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 322, 'Lâm Bình', 58);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 323, 'Lâm Hà', 38);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 324, 'Lâm Thao', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 325, 'Lấp Vò', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 326, 'Lập Thạch', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 327, 'Lê Chân', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 328, 'Lệ Thủy', 46);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 329, 'Liên Chiểu', 16);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 330, 'Long Biên', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 331, 'Long Điền', 63);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 332, 'Long Hồ', 61);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 333, 'Long Khánh', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 334, 'Long Mỹ', 26);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 335, 'Long Phú', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 336, 'Long Thành', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 337, 'Long Xuyên', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 338, 'Lộc Bình', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 339, 'Lộc Hà', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 340, 'Lộc Ninh', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 341, 'Lục Nam', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 342, 'Lục Ngạn', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 343, 'Lục Yên', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 344, 'Lương Sơn', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 345, 'Lương Tài', 7);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 346, 'Lý Nhân', 27);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 347, 'Lý Sơn', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 348, 'Mai Châu', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 349, 'Mai Sơn', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 350, 'Mang Thít', 61);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 351, 'Mang Yang', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 352, "M'Đrăk", 15);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 353, 'Mèo Vạc', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 354, 'Mê Linh', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 355, 'Minh Hóa', 46);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 356, 'Minh Long', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 357, 'Mỏ Cày Bắc', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 358, 'Mỏ Cày Nam', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 359, 'Móng Cái', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 360, 'Mộ Đức', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 361, 'Mộc Châu', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 362, 'Mộc Hóa', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 363, 'Mù Căng Chải', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 364, 'Mường Ảng', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 365, 'Mường Chà', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 366, 'Mường Khương', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 367, 'Mường La', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 368, 'Mường Lát', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 369, 'Mường Lay', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 370, 'Mường Nhé', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 371, 'Mường Tè', 37);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 372, 'Mỹ Đức', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 373, 'Mỹ Hào', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 374, 'Mỹ Lộc', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 375, 'Mỹ Tho', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 376, 'Mỹ Tú', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 377, 'Mỹ Xuyên', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 378, 'Na Hang', 58);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 379, 'Na Rì', 2);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 380, 'Nam Đàn', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 381, 'Nam Định', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 382, 'Nam Đông', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 383, 'Nam Giang', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 384, 'Nam Sách', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 385, 'Nam Trà My', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 386, 'Nam Trực', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 387, 'Năm Căn', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 388, 'Nga Sơn', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 389, 'Ngã Bảy', 26);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 390, 'Ngã Năm', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 391, 'Ngân Sơn', 2);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 392, 'Nghi Lộc', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 393, 'Nghi Xuân', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 394, 'Nghĩa Đàn', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 395, 'Nghĩa Hành', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 396, 'Nghĩa Hưng', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 397, 'Nghĩa Lộ', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 398, 'Ngọc Hiển', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 399, 'Ngọc Hồi', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 400, 'Ngọc Lặc', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 401, 'Ngô Quyền', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 402, 'Ngũ Hành Sơn', 16);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 403, 'Nguyên Bình', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 404, 'Nha Trang', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 405, 'Nhà Bè', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 406, 'Nho Quan', 41);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 407, 'Nhơn Trạch', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 408, 'Như Thanh', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 409, 'Như Xuân', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 410, 'Ninh Bình', 41);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 411, 'Ninh Giang', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 412, 'Ninh Hải', 43);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 413, 'Ninh Hòa', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 414, 'Ninh Kiều', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 415, 'Ninh Phước', 43);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 416, 'Ninh Sơn', 43);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 417, 'Nông Cống', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 418, 'Nông Sơn', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 419, 'Núi Thành', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 420, 'Ô Môn', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 421, 'Pác Nặm', 2);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 422, 'Phan Rang-Tháp Chàm', 43);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 423, 'Phan Thiết', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 424, 'Phong Điền', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 425, 'Phong Điền', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 426, 'Phong Thổ', 37);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 427, 'Phổ Yên', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 428, 'Phú Bình', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 429, 'Phú Giáo', 3);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 430, 'Phú Hòa', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 431, 'Phú Lộc', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 432, 'Phú Lương', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 433, 'Phú Nhuận', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 434, 'Phú Ninh', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 435, 'Phú Quý', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 436, 'Phú Quốc', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 437, 'Phú Tân', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 438, 'Phú Tân', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 439, 'Phú Thiện', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 440, 'Phú Thọ', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 441, 'Phú Vang', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 442, 'Phú Xuyên', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 443, 'Phù Cát', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 444, 'Phù Cừ', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 445, 'Phù Mỹ', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 446, 'Phù Ninh', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 447, 'Phù Yên', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 448, 'Phủ Lý', 27);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 449, 'Phúc Thọ', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 450, 'Phúc Yên', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 451, 'Phục Hòa', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 452, 'Phụng Hiệp', 26);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 453, 'Phước Long', 8);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 454, 'Phước Long', 6);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 455, 'Phước Sơn', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 456, 'Pleiku', 20);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 457, 'Quan Hóa', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 458, 'Quan Sơn', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 459, 'Quản Bạ', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 460, 'Quang Bình', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 461, 'Quảng Điền', 59);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 462, 'Quảng Ngãi', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 463, 'Quảng Ninh', 46);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 464, 'Quảng Trạch', 46);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 465, 'Quảng Trị', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 466, 'Quảng Yên', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 467, 'Quảng Uyên', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 468, 'Quảng Xương', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 469, 'Quận 1', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 470, 'Quận 2', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 471, 'Quận 3', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 472, 'Quận 4', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 473, 'Quận 5', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 474, 'Quận 6', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 475, 'Quận 7', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 476, 'Quận 8', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 477, 'Quận 9', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 478, 'Quận 10', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 479, 'Quận 11', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 480, 'Quận 12', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 481, 'Quế Phong', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 482, 'Quế Sơn', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 483, 'Quế Võ', 7);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 484, 'Qui Nhơn', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 485, 'Quốc Oai', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 486, 'Quỳ Châu', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 487, 'Quỳ Hợp', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 488, 'Quỳnh Lưu', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 489, 'Quỳnh Nhai', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 490, 'Quỳnh Phụ', 53);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 491, 'Rạch Giá', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 492, 'Sa Đéc', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 493, 'Sa Pa', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 494, 'Sa Thầy', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 495, 'Sầm Sơn', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 496, 'Si Ma Cai', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 497, 'Sìn Hồ', 37);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 498, 'Sóc Sơn', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 499, 'Sóc Trăng', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 500, 'Sông Cầu', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 501, 'Sông Công', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 502, 'Sông Hinh', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 503, 'Sông Lô', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 504, 'Sông Mã', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 505, 'Sốp Cộp', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 506, 'Sơn Động', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 507, 'Sơn Dương', 58);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 508, 'Sơn Hà', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 509, 'Sơn Hòa', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 510, 'Sơn La', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 511, 'Sơn Tây', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 512, 'Sơn Tây', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 513, 'Sơn Tịnh', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 514, 'Sơn Trà', 16);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 515, 'Tam Bình', 61);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 516, 'Tam Dương', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 517, 'Tam Đảo', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 518, 'Tam Điệp', 41);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 519, 'Tam Đường', 37);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 520, 'Tam Kỳ', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 521, 'Tam Nông', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 522, 'Tam Nông', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 523, 'Tánh Linh', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 524, 'Tân An', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 525, 'Tân Biên', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 526, 'Tân Bình', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 527, 'Tân Châu', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 528, 'Tân Châu', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 529, 'Tân Hiệp', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 530, 'Tân Hồng', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 531, 'Tân Hưng', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 532, 'Tân Kỳ', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 533, 'Tân Lạc', 22);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 534, 'Tân Phú', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 535, 'Tân Phú', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 536, 'Tân Phú Đông', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 537, 'Tân Phước', 54);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 538, 'Tân Sơn', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 539, 'Tân Thành', 63);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 540, 'Tân Thạnh', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 541, 'Tân Trụ', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 542, 'Tân Uyên', 3);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 543, 'Tân Uyên', 37);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 544, 'Tân Yên', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 545, 'Tây Giang', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 546, 'Tây Hòa', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 547, 'Tây Hồ', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 548, 'Tây Ninh', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 549, 'Tây Sơn', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 550, 'Tây Trà', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 551, 'Thạch An', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 552, 'Thạch Hà', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 553, 'Thạch Thành', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 554, 'Thạch Thất', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 555, 'Thái Bình', 53);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 556, 'Thái Hòa', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 557, 'Thái Nguyên', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 558, 'Thái Thụy', 53);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 559, 'Than Uyên', 37);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 560, 'Thanh Ba', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 561, 'Thanh Bình', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 562, 'Thanh Chương', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 563, 'Thanh Hà', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 564, 'Thanh Hóa', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 565, 'Thanh Khê', 16);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 566, 'Thanh Liêm', 27);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 567, 'Thanh Miện', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 568, 'Thanh Oai', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 569, 'Thanh Sơn', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 570, 'Thanh Thủy', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 571, 'Thanh Trì', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 572, 'Thanh Xuân', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 573, 'Thạnh Hóa', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 574, 'Thạnh Phú', 9);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 575, 'Thạnh Trị', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 576, 'Tháp Mười', 19);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 577, 'Thăng Bình', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 578, 'Thiệu Hóa', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 579, 'Thọ Xuân', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 580, 'Thoại Sơn', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 581, 'Thông Nông', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 582, 'Thống Nhất', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 583, 'Thốt Nốt', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 584, 'Thới Bình', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 585, 'Thới Lai', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 586, 'Thủ Dầu Một', 3);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 587, 'Thủ Đức', 23);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 588, 'Thủ Thừa', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 589, 'Thuận An', 3);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 590, 'Thuận Bắc', 43);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 591, 'Thuận Châu', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 592, 'Thuận Nam', 43);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 593, 'Thuận Thành', 7);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 594, 'Thuỷ Nguyên', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 595, 'Thường Tín', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 596, 'Thường Xuân', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 597, 'Tiên Du', 7);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 598, 'Tiền Hải', 53);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 599, 'Tiên Lãng', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 600, 'Tiên Lữ', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 601, 'Tiên Phước', 49);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 602, 'Tiên Yên', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 603, 'Tiểu Cần', 60);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 604, 'Tĩnh Gia', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 605, 'Tịnh Biên', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 606, 'Trà Bồng', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 607, 'Trà Cú', 60);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 608, 'Trà Lĩnh', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 609, 'Trà Ôn', 61);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 610, 'Trà Vinh', 60);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 611, 'Trạm Tấu', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 612, 'Tràng Định', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 613, 'Trảng Bàng', 56);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 614, 'Trảng Bom', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 615, 'Trấn Yên', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 616, 'Trần Đề', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 617, 'Trần Văn Thời', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 618, 'Tri Tôn', 1);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 619, 'Triệu Phong', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 620, 'Triệu Sơn', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 621, 'Trùng Khánh', 11);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 622, 'Trực Ninh', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 623, 'Trường Sa', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 624, 'Tủa Chùa', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 625, 'Tuần Giáo', 14);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 626, 'Tu Mơ Rông', 34);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 627, 'Tuy An', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 628, 'Tuy Đức', 18);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 629, 'Tuy Hòa', 45);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 630, 'Tuy Phong', 10);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 631, 'Tuy Phước', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 632, 'Tuyên Hóa', 46);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 633, 'Tuyên Quang', 58);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 634, 'Tư Nghĩa', 47);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 635, 'Tứ Kỳ', 24);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 636, 'Từ Liêm', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 637, 'Từ Sơn', 7);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 638, 'Tương Dương', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 639, 'U Minh', 12);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 640, 'U Minh Thượng', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 641, 'Uông Bí', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 642, 'Ứng Hòa', 21);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 643, 'Vạn Ninh', 33);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 644, 'Văn Bàn', 36);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 645, 'Văn Chấn', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 646, 'Văn Giang', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 647, 'Vãn Lãng', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 648, 'Văn Lâm', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 649, 'Văn Quan', 39);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 650, 'Văn Yên', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 651, 'Vân Canh', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 652, 'Vân Đồn', 48);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 653, 'Vị Thanh', 26);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 654, 'Vị Thủy', 26);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 655, 'Vị Xuyên', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 656, 'Việt Trì', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 657, 'Việt Yên', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 658, 'Vinh', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 659, 'Vĩnh Bảo', 28);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 660, 'Vĩnh Châu', 52);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 661, 'Vĩnh Cửu', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 662, 'Vĩnh Hưng', 35);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 663, 'Vĩnh Linh', 50);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 664, 'Vĩnh Long', 61);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 665, 'Vĩnh Lộc', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 666, 'Vĩnh Lợi', 6);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 667, 'Vĩnh Thạnh', 4);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 668, 'Vĩnh Thạnh', 13);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 669, 'Vĩnh Thuận', 32);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 670, 'Vĩnh Tường', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 671, 'Vĩnh Yên', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 672, 'Võ Nhai', 57);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 673, 'Vũ Quang', 29);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 674, 'Vũ Thư', 53);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 675, 'Vụ Bản', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 676, 'Vũng Liêm', 61);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 677, 'Vũng Tàu', 63);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 678, 'Xín Mần', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 679, 'Xuân Lộc', 17);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 680, 'Xuân Trường', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 681, 'Xuyên Mộc', 63);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 682, 'Ý Yên', 42);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 683, 'Yên Bái', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 684, 'Yên Bình', 64);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 685, 'Yên Châu', 51);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 686, 'Yên Dũng', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 687, 'Yên Định', 55);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 688, 'Yên Khánh', 41);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 689, 'Yên Lạc', 62);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 690, 'Yên Lập', 44);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 691, 'Yên Minh', 25);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 692, 'Yên Mô', 41);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 693, 'Yên Mỹ', 31);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 694, 'Yên Phong', 7);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 695, 'Yên Sơn', 58);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 696, 'Yên Thành', 40);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 697, 'Yên Thế', 5);
  db.run('INSERT INTO districts(districtId, name, provinceId) VALUES(?,?,?);', 698, 'Yên Thủy', 22);
}
